### ISSUE TITLE
Diğer entegrasyon alanları

### ISSUE THREAD

**Issue by c0b41** [ercancavusoglu/aras-cargo-entegrasyon#2]
Aras kargoda takip verileri göndermek dışında başka alanlarda var bunlarda eklenirse paket'e güzel olur

**Comment by ercancavusoglu** [comment]
Şimdilik ihtiyaca göre bi başlangıç yaptım, bahsettiğiniz gibi eklemeler olacaktır.

**Comment by c0b41** [comment]
Boş bir vaktimde pull request halinde eklemelerde bulanacağım inş :)
