### ISSUE TITLE
Curl yerine SoapClient

### ISSUE THREAD

**Issue by abdlkrmdlgr** [ercancavusoglu/aras-cargo-entegrasyon#4]
Hocam merhaba,

Curl ile xml post yerine soap client üzerinden objekt parametre geçilebilir mi? Aras tarafında bir dar bogaz mi var bununla ilgili?

**Comment by ercancavusoglu** [comment]
Merhaba Abdullah, yıllar önce bu tarz yazmıştım, projenin aciliyetinden dolayı soap ile uğraşmadım açıkcası. Bi zorluk olacağını zannetmem. Php ile soap çalışınca bazı dosyalardaki soap definitions ları manuel düzenlemek gerekebiliyor. Onları handle ederseniz zahmetli ama daha temiz olacaktır.
